# Add custom window config in this file.
# Assign Betterbird to a specific workspawindowrulev2 = workspace 6, class:^(?!(chrome-gemini.google.com__-Default)$).* , onworkspace:1
# # Rule to put Gemini in the special workspace


# Scratchpads 
#
# EPIC SHIZZLE
# 


# Gemini Rule
windowrulev2 = workspace special:gemini, class:.*gemini.*
# Gmail: Super + M
bind = SUPER, A, togglespecialworkspace, gemini
# check if proces exists to avoid duplicates
bind = SUPER, A, exec,  ~/.config/hypr/scripts/launch_app.sh "chrome-gemini.google.com" "https://gemini.google.com"

# Gmail Rule
windowrulev2 = workspace special:mail, class:^(chrome-mail.google.com__-Default)$
# Gmail: Super + M
bind = SUPER, M, togglespecialworkspace, mail
# check if proces exists to avoid duplicates
bind = SUPER, M, exec, ~/.config/hypr/scripts/launch_app.sh "chrome-mail.google.com" "https://mail.google.com"


# Calendar Rule
windowrulev2 = workspace special:calendar, opacity 0.95 0.90, idleinhibit focus, class:(chrome-calendar.google.com__-Default)
# Calendar: Super + C
bind = SUPER SHIFT, C, togglespecialworkspace, calendar
# check if proces exists to avoid duplicates
bind = SUPER SHIFTi, C, exec, ~/.config/hypr/scripts/launch_app.sh "chrome-calendar.google.com" "https://calendar.google.com"

# Google Keeop Rule
windowrulev2 = workspace special:calendar, opacity 0.95 0.90, idleinhibit focus, class:(chrome-keep.google.com__-Default)
# Calendar: Super + C
bind = SUPER, N, togglespecialworkspace, notes
# check if proces exists to avoid duplicates
bind = SUPER, N, exec, ~/.config/hypr/scripts/launch_app.sh "chrome-keep.google.com" "https://keep.google.com"
