# ─── App-specific Window Rules ───────────────────────────────────────────────

source = ~/.config/hypr/apps/bitwarden.conf
source = ~/.config/hypr/apps/browser.conf
source = ~/.config/hypr/apps/jetbrains.conf
source = ~/.config/hypr/apps/moonlight.conf
source = ~/.config/hypr/apps/pip.conf
source = ~/.config/hypr/apps/qemu.conf
source = ~/.config/hypr/apps/retroarch.conf
source = ~/.config/hypr/apps/steam.conf
source = ~/.config/hypr/apps/terminals.conf
source = ~/.config/hypr/apps/tui.conf
